
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASC AVG BY COLON COMMA COUNT DESC EQUALS FIND FROM IDENTIFIER JOIN LBRACKET LPAREN ON RBRACKET RPAREN SELECT STAR STRING WHEREquery : select_query\n             | find_queryselect_query : SELECT fields optional_sorting WHERE conditions FROM IDENTIFIER\n                    | SELECT fields optional_sorting WHERE conditions FROM join_expressionfind_query : FIND agg_func optional_sorting BY IDENTIFIER FROM IDENTIFIER\n                  | FIND agg_func optional_sorting BY IDENTIFIER FROM join_expressionagg_func : AVG\n                | COUNTagg_func : AVG LPAREN IDENTIFIER RPAREN\n                | COUNT LPAREN IDENTIFIER RPARENfields : field\n              | field COMMA fieldsfield : IDENTIFIER\n             | STARoptional_sorting : LBRACKET sort_order RBRACKET\n                        | sort_order : ASC\n                  | DESCconditions : condition\n                  | condition COMMA conditionscondition : IDENTIFIER EQUALS STRING\n                 | IDENTIFIER EQUALS IDENTIFIERtables : IDENTIFIER\n              | IDENTIFIER COMMA tablesjoin_expression : JOIN tables ON join_conditionsjoin_condition : IDENTIFIER COLON IDENTIFIERjoin_conditions : join_condition\n                       | join_condition COMMA join_conditions'
    
_lr_action_items = {'SELECT':([0,],[4,]),'FIND':([0,],[5,]),'$end':([1,2,3,38,39,44,45,50,51,56,57,],[0,-1,-2,-3,-4,-5,-6,-25,-27,-28,-26,]),'IDENTIFIER':([4,15,17,18,19,24,34,35,36,37,40,48,49,54,55,],[7,7,25,26,28,31,38,41,28,44,47,52,47,52,57,]),'STAR':([4,15,],[9,9,]),'AVG':([5,],[11,]),'COUNT':([5,],[12,]),'LBRACKET':([6,7,8,9,10,11,12,23,32,33,],[14,-13,-11,-14,14,-7,-8,-12,-9,-10,]),'WHERE':([6,7,8,9,13,23,30,],[-16,-13,-11,-14,19,-12,-15,]),'COMMA':([7,8,9,29,41,42,47,51,57,],[-13,15,-14,36,-22,-21,49,54,-26,]),'BY':([10,11,12,16,30,32,33,],[-16,-7,-8,24,-15,-9,-10,]),'LPAREN':([11,12,],[17,18,]),'ASC':([14,],[21,]),'DESC':([14,],[22,]),'RBRACKET':([20,21,22,],[30,-17,-18,]),'RPAREN':([25,26,],[32,33,]),'FROM':([27,29,31,41,42,43,],[34,-19,37,-22,-21,-20,]),'EQUALS':([28,],[35,]),'JOIN':([34,37,],[40,40,]),'STRING':([35,],[42,]),'ON':([46,47,53,],[48,-23,-24,]),'COLON':([52,],[55,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'select_query':([0,],[2,]),'find_query':([0,],[3,]),'fields':([4,15,],[6,23,]),'field':([4,15,],[8,8,]),'agg_func':([5,],[10,]),'optional_sorting':([6,10,],[13,16,]),'sort_order':([14,],[20,]),'conditions':([19,36,],[27,43,]),'condition':([19,36,],[29,29,]),'join_expression':([34,37,],[39,45,]),'tables':([40,49,],[46,53,]),'join_conditions':([48,54,],[50,56,]),'join_condition':([48,54,],[51,51,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select_query','query',1,'p_query','db.py',57),
  ('query -> find_query','query',1,'p_query','db.py',58),
  ('select_query -> SELECT fields optional_sorting WHERE conditions FROM IDENTIFIER','select_query',7,'p_select_query','db.py',62),
  ('select_query -> SELECT fields optional_sorting WHERE conditions FROM join_expression','select_query',7,'p_select_query','db.py',63),
  ('find_query -> FIND agg_func optional_sorting BY IDENTIFIER FROM IDENTIFIER','find_query',7,'p_find_query','db.py',82),
  ('find_query -> FIND agg_func optional_sorting BY IDENTIFIER FROM join_expression','find_query',7,'p_find_query','db.py',83),
  ('agg_func -> AVG','agg_func',1,'p_agg_func','db.py',108),
  ('agg_func -> COUNT','agg_func',1,'p_agg_func','db.py',109),
  ('agg_func -> AVG LPAREN IDENTIFIER RPAREN','agg_func',4,'p_agg_func_with_args','db.py',113),
  ('agg_func -> COUNT LPAREN IDENTIFIER RPAREN','agg_func',4,'p_agg_func_with_args','db.py',114),
  ('fields -> field','fields',1,'p_fields','db.py',118),
  ('fields -> field COMMA fields','fields',3,'p_fields','db.py',119),
  ('field -> IDENTIFIER','field',1,'p_field','db.py',126),
  ('field -> STAR','field',1,'p_field','db.py',127),
  ('optional_sorting -> LBRACKET sort_order RBRACKET','optional_sorting',3,'p_optional_sorting','db.py',131),
  ('optional_sorting -> <empty>','optional_sorting',0,'p_optional_sorting','db.py',132),
  ('sort_order -> ASC','sort_order',1,'p_sort_order','db.py',147),
  ('sort_order -> DESC','sort_order',1,'p_sort_order','db.py',148),
  ('conditions -> condition','conditions',1,'p_conditions','db.py',177),
  ('conditions -> condition COMMA conditions','conditions',3,'p_conditions','db.py',178),
  ('condition -> IDENTIFIER EQUALS STRING','condition',3,'p_condition','db.py',182),
  ('condition -> IDENTIFIER EQUALS IDENTIFIER','condition',3,'p_condition','db.py',183),
  ('tables -> IDENTIFIER','tables',1,'p_tables','db.py',191),
  ('tables -> IDENTIFIER COMMA tables','tables',3,'p_tables','db.py',192),
  ('join_expression -> JOIN tables ON join_conditions','join_expression',4,'p_join_expression','db.py',196),
  ('join_condition -> IDENTIFIER COLON IDENTIFIER','join_condition',3,'p_join_condition','db.py',204),
  ('join_conditions -> join_condition','join_conditions',1,'p_join_conditions','db.py',208),
  ('join_conditions -> join_condition COMMA join_conditions','join_conditions',3,'p_join_conditions','db.py',209),
]
